_target_: src.model.feature_processor.DualFeatureProcessorTwoStage
hidden_dim: ${architecture.hidden_dim}
activation:
  _target_: torch.nn.PReLU
lr_mapping_type: ${architecture.lr_mapping_type}
tile_size_per_channel: [4, 8]