_target_: src.model.feature_processor.DualFeatureProcessorWithZSim
hidden_dim: ${architecture.hidden_dim}
use_lr_feature: ${architecture.use_lr_feature}
use_similarity_feature: ${architecture.use_similarity_feature}
lr_mapping_type: ${architecture.lr_mapping_type}
use_z_similarity_feature: true
z_mapping_type: identity
