_target_: src.model.decoder.UnetV3
encoder_depth: 4
hidden_size: 64
kernel_sizes: [4, 4, 4]
strides: [2, 2, 2]
se_ratio: 4
num_res_blocks: 1
attend_to_frequency_dim: false
frequency_smooth_kernel_size: 1
temporal_smooth_kernel_size: 3
