_target_: src.model.eeg_encoder.EfficientNet1dV2
depth_multiplier: 4
ds_conv_se_ratio: 4
ir_conv_se_ratio: 16
stem_kernel_size: 3
stem_pool_size: 2
kernel_sizes: [3, 3, 5, 5, 3]
layers: [1, 2, 3, 3, 3]
hidden_dims: [32, 16, 24, 40, 64, 64]
strides: [1, 2, 2, 2, 2]
frame_offset: 744 # 800 - (512 - 400) // 2
num_frames: 512
skip_in_block: true
skip_in_layer: false
drop_path_rate: 0.0
use_ds_conv: false
se_after_dw_conv: true
grad_checkpointing: false
use_channel_mixer: true
channel_mixer_kernel_size: 3
mixer_type: sc
