_target_: src.model.eeg_encoder.EfficientNet1dYu4u
hidden_dim: 32
depth_multiplier: 4
stem_kernel_size: 5
kernel_sizes: [3, 3, 5, 5, 3, 3]
pool_sizes: [2, 2, 2, 2, 2, 2]
layers: 3
skip_in_block: true
skip_in_layer: true
drop_path_rate: 0.0
use_ds_conv: false
se_after_dw_conv: true
channel_mixer_kernel_size: 3
input_mask: true
