_target_: src.model.eeg_encoder.ResNet1d
sep_kernel_sizes: [3, 5, 7, 9]
kernel_size: 3
hidden_dim: 64
se_ratio: 2
stem_conv_kernel_size: 4
stem_conv_stride: 4
res_block_size: 6
stride_per_block: 1
num_gru_layers: 1