defaults:
  - baseline
  - _self_

exp_name: exp004
description: apply randomly swap LR channels

trainer:
  transform:
    _target_: src.transform.Compose
    transforms:
      - _target_: src.transform.SwapLr
        p: 0.5