defaults:
  - baseline
  - override architecture/model/sample_collator: tile_collator
  - override architecture/model/sample_aggregator: attention_pooling_over_spec
  - override architecture/model/head: label_aligned_head_v3
  - _self_

exp_name: exp015
description: baseline decoder

trainer:
  lr: 2.5e-4
  num_samples_per_eeg: 4
architecture:
  model:
    sample_aggregator:
      hidden_size: 64
      attend_to_frequency_dim: false
