defaults:
  - baseline
  - override architecture/model/head: label_aligned_head_v2
  - _self_

exp_name: exp018
description: exp016 + reverse sequence

architecture:
  model:
    adapters:
      - _target_: src.model.adapter.TilingAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [2.0, 8.0] # 256 x 256

trainer:
  transform:
    _target_: src.transform.Compose
    transforms:
      - _target_: src.transform.ReverseSequence
        p: 0.5
