defaults:
  - baseline_v3
  - architecture/model/eeg_adapter: eeg_dual_per_channel_collator
  - architecture/model/eeg_encoder: resnet1d
  - architecture/model/eeg_feature_processor: eeg_dual_per_channel
  - override architecture/model/feature_extractor: channel_collator
  - override architecture/model/head: mlp_head
  - _self_

exp_name: ???
description: ???

architecture:
  model_class:
    _target_: src.model.hms_model.hms_model_1d.HmsModel1d
  model_checker:
    _target_: src.model.hms_model.hms_model_1d.check_model
  in_channels: 2
  input_mask: true
