defaults:
  - baseline_v4
  - architecture/model/eeg_adapter: eeg_dual_stacking_collator
  - architecture/model/eeg_encoder: efficientnet1d
  - override architecture/model/feature_processor: contrastive_dual_feature_processor
  - _self_

exp_name: ???
description: ???

architecture:
  model:
    eeg_encoder:
      se_after_dw_conv: true
    feature_processor:
      num_eeg_channels: 10
  in_channels: null
  in_channels_eeg: 20
  in_channels_spec: 2
  model_class:
    _target_: src.model.hms_model.hms_model_contrastive.HmsModelContrastive
  model_checker:
    _target_: src.model.hms_model.hms_model_contrastive.check_model

trainer:
  trainer_class:
    _target_: src.trainer.ContrastiveTrainer
