defaults:
  - baseline_v2
  - _self_

exp_name: exp037
description: exp033 + channel permutation(p=0.8)

architecture:
  model:
    feature_extractor:
      cutoff_freqs: [0.5, null]
    adapters:
      - _target_: src.model.adapter.ConstantNormalizer
      - _target_: src.model.adapter.DualCanvasAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [1.0, 2.0]
    bg_adapters:
      - _target_: src.model.bg_adapter.BgConstantNormalizer
      - _target_: src.model.bg_adapter.BgDualCanvasAggregator
      - _target_: src.model.bg_adapter.BgResizeTransform
        size: [128, 512]
    merger:
      _target_: src.model.merger.MergeFreq
  in_channels: 2
  use_bg_spec: true
  spec_cropped_duration: 128

trainer:
  weight_decay: 1e-5
  data:
    input_keys: [eeg, cqf, spec]
  transform:
    _target_: src.transform.Compose
    transforms:
      - _target_: src.transform.SwapLr
        p: 0.5
      - _target_: src.transform.ChannelPermutation
        p: 0.8
      - _target_: src.transform.Cutout1d
        p: 0.3
        max_length: 128
        num_cutouts: 4
