defaults:
  - baseline_v2
  - _self_

exp_name: exp038
description: exp033 + b2 backbone

architecture:
  model:
    feature_extractor:
      cutoff_freqs: [0.5, null]
    adapters:
      - _target_: src.model.adapter.ConstantNormalizer
      - _target_: src.model.adapter.DualCanvasAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [1.0, 2.0]
    bg_adapters:
      - _target_: src.model.bg_adapter.BgConstantNormalizer
      - _target_: src.model.bg_adapter.BgDualCanvasAggregator
      - _target_: src.model.bg_adapter.BgResizeTransform
        size: [128, 512]
    merger:
      _target_: src.model.merger.MergeFreq
    encoder:
      name: efficientnet_b2
  in_channels: 2
  use_bg_spec: true
  spec_cropped_duration: 128

trainer:
  weight_decay: 1e-5
  data:
    input_keys: [eeg, cqf, bg_spec]
