defaults:
  - baseline_v2
  - _self_

exp_name: exp036
description: exp033 + TimeFreqMasking(p=0.3)

architecture:
  model:
    feature_extractor:
      cutoff_freqs: [0.5, null]
    spec_transform:
      _target_: src.augmentation.ChannelSyncedTimeFreqMasking
      time_mask_ratio: 0.2
      freq_mask_ratio: 0.2
      num_time_masks: 2
      num_freq_masks: 2
      mask_value: -40.0
      p: 1.0
    adapters:
      - _target_: src.model.adapter.ConstantNormalizer
      - _target_: src.model.adapter.DualCanvasAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [1.0, 2.0]
    bg_adapters:
      - _target_: src.model.bg_adapter.BgConstantNormalizer
      - _target_: src.model.bg_adapter.BgDualCanvasAggregator
      - _target_: src.model.bg_adapter.BgResizeTransform
        size: [128, 512]
    merger:
      _target_: src.model.merger.MergeFreq
  in_channels: 2
  use_bg_spec: true

trainer:
  weight_decay: 1e-5
  data:
    input_keys: [eeg, cqf, spec]
  train_dataset:
    spec_cropped_duration: 128
  valid_dataset:
    spec_cropped_duration: 128
