defaults:
  - baseline
  - override architecture/model/head: label_aligned_head_v2
  - override trainer/pseudo_label: with_pl
  - _self_

exp_name: exp021
description: exp019 + pseudo label

architecture:
  model:
    adapters:
      - _target_: src.model.adapter.DualTilingAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [2.0, 8.0] # 256 x 256

  in_channels: 3
  is_dual: true

trainer:
  transform:
    _target_: src.transform.Compose
    transforms:
      - _target_: src.transform.SwapLr
        p: 0.5
      - _target_: src.transform.ReverseSequence
        p: 0.5
  pseudo_label:
    teacher_ensemble_name: exp019_cf
    max_drop_ratio: 0.25
    saturated_epochs: 3
