defaults:
  - baseline_v3_wmt_bg
  - _self_

exp_name: exp063
description: exp062 + instance norm

architecture:
  model:
    adapters:
      - _target_: src.model.adapter.InstanceNormalizer
      - _target_: src.model.adapter.DualWeightedMeanTilingAggregator
      - _target_: src.model.adapter.ResizeTransform
        scale_factor: [1.0, 2.0]
    bg_adapters:
      - _target_: src.model.bg_adapter.BgInstanceNormalizer
      - _target_: src.model.bg_adapter.BgResizeTransform
        size: [128, 256]
      - _target_: src.model.bg_adapter.BgDualTilingAggregator
    merger:
      _target_: src.model.merger.MergeTime
  in_channels: 2
  input_mask: true
  recover_dual: true
  lr_mapping_type: max-min
  use_bg_spec: true
