hydra:
  run:
    dir: ${env.data_dir}/single/${job_name}/${phase}
  sweep:
    dir: ${dir.output_dir}/multirun/${job_name}/${phase}
    subdir: ${hydra.job.override_dirname}
  job:
    name: ${job_name}
    chdir: true
    config:
      override_dirname:
        exclude_keys:
          - verbose
          - debug

defaults:
  - env: local
  - preprocess: with_cqf
  - split: gkfold5
  - trainer/optimizer: adamw
  - architecture/model: hms_model
  - architecture/model/feature_extractor: wave2spec
  - architecture/model/encoder: timm_encoder
  - architecture/model/head: simple_head
  - _self_

trainer:
  epochs: 10
  lr: 1e-3
  scheduler:
    warmup_ratio: 0.0
  data:
    target_key: label
    pred_key: pred
    weight_key: weight
    input_keys: [eeg, cqf]

architecture:
  model:
    adaptors:
      - _target_: src.model.adaptor.mean.Mean
      - _target_: src.model.adaptor.resize.Resize
        scale_factor: [2.0, 8.0]
    encoder:
      name: efficientnet_b0
      in_channels: ${architecture.in_channels}
    head:
      out_channels: ${architecture.out_channels}
  in_channels: 5
  out_channels: 6


job_name: ???
phase: train # train or test
dry_run: false
debug: false
cleanup: true