_target_: src.model.feature_extractor.ChannelCollator
sampling_rate: 200
cutoff_freqs: [0.5, 50]
apply_mask: true
probe_groups:
    L1: [Fp1, F7, T3, T5, O1]
    L2: [Fp1, F3, C3, P3, O1]
    LZ: [Fz, Cz, Pz]
    R1: [Fp2, F8, T4, T6, O2]
    R2: [Fp2, F4, C4, P4, O2]
    RZ: [Fz, Cz, Pz]
down_sample_rate: 5
down_sample_after_filter: false
