_target_: src.model.feature_extractor.Wave2Wavegram
channel_collator:
  _target_: src.model.feature_extractor.ChannelCollator
  sampling_rate: 200
  cutoff_freqs: ${architecture.model.feature_extractor.cutoff_freqs}
  apply_mask: ${architecture.model.feature_extractor.apply_mask}
  down_sample_rate: 5
  down_sample_after_filter: false
  reject_freq: null
wavegram:
  _target_: src.model.feature_extractor.module.EfficientWavegram
  in_channels: 1
  out_channels: 1
  stem_kernel_size: 3
  stem_stride: 1
  num_filter_banks: 64
  layers: [2, 2, 2, 2]
  kernel_sizes: [3, 3, 3, 3]
  hidden_dims: [32, 16, 24, 40, 64]
  strides: [2, 2, 2, 2]
  depth_multiplier: 4
  se_ratio: 16
win_length: 64
cutoff_freqs: [0.5, 50]
apply_mask: true
downsample_mode: linear
expand_mask: true
