_target_: src.model.feature_extractor.Wave2Spectrogram
channel_collator:
  _target_: src.model.feature_extractor.ChannelCollator
  sampling_rate: 200
  cutoff_freqs: ${architecture.model.feature_extractor.cutoff_freqs}
  apply_mask: ${architecture.model.feature_extractor.apply_mask}
  down_sample_rate: 5
  down_sample_after_filter: false
  reject_freq: null
wave2spec:
  _target_: src.model.feature_extractor.module.MelSpec
  sampling_rate: 40
  n_fft: 256
  win_length: 32
  hop_length: 8
  frequency_lim: [0, 20]
  db_cutoff: 60
  db_offset: 0
  n_mels: 128
  window_fn: hann_window
  norm: [0, 1]
cutoff_freqs: [0.5, 50]
apply_mask: True
downsample_mode: linear
