_target_: src.model.feature_extractor.Wave2Wavegram
wavegram:
  _target_: src.model.feature_extractor.module.Wavegram
  in_channels: 1
  out_channels: 1
  stem_kernel_size: 3
  stem_stride: 1
  hidden_dims: [64, 64, 64, 128, 128]
  num_filter_banks: 64
sampling_rate: 40
win_length: 64
cutoff_freqs: [0.5, 50]
apply_mask: true
downsample_mode: linear
expand_mask: true
