_target_: src.model.feature_extractor.Wave2Wavegram
wavegram:
  _target_: src.model.feature_extractor.module.Wavenet
  in_channels: 1
  out_channels: 8
  stem_kernel_size: 3
  stem_stride: 1
  hidden_dim: 64
  num_filter_banks: 64
  bottleneck_ratio: 8
sampling_rate: 40
win_length: 64
cutoff_freqs: [0.5, 50]
apply_mask: true
downsample_mode: linear
expand_mask: true
freq_mask_param: 16
time_mask_param: 32
