_target_: src.model.feature_extractor.Wave2Wavegram
channel_collator:
  _target_: src.model.feature_extractor.ChannelCollator
  sampling_rate: 200
  cutoff_freqs: ${architecture.model.feature_extractor.cutoff_freqs}
  apply_mask: ${architecture.model.feature_extractor.apply_mask}
  down_sample_rate: 5
  down_sample_after_filter: false
  reject_freq: null
wavegram:
  _target_: src.model.feature_extractor.module.Wavegram
  in_channels: 1
  out_channels: 32
  stem_kernel_size: 3
  stem_stride: 1
  hidden_dims: [64, 64, 64, 128, 128]
  num_filter_banks: 64
sampling_rate: 40
win_length: 64
cutoff_freqs: [0.5, 50]
apply_mask: true
downsample_mode: linear
expand_mask: true
freq_mask_param: 16
time_mask_param: 32
