_target_: src.model.feature_extractor.Wave2Panns
wave2spec:
  _target_: src.model.feature_extractor.module.MelSpec
  sampling_rate: 40
  n_fft: 256
  win_length: 64
  hop_length: 16
  frequency_lim: [0, 20]
  db_cutoff: 60
  db_offset: 0
  n_mels: 64
  window_fn: hann_window
  norm: [-37.52, 16.10]
wavegram:
  _target_: src.model.feature_extractor.module.Wavegram
  in_channels: 1
  out_channels: 1
  stem_kernel_size: 3
  stem_stride: 1
  hidden_dims: [64, 64, 64, 128, 128]
  num_filter_banks: 64
cutoff_freqs: [0.5, 50]
apply_mask: false
downsample_mode: linear
expand_mask: true
