_target_: src.model.feature_extractor.Wave2Wavegram
sampling_rate: 40
num_filter_banks: 64
win_length: 64
cutoff_freqs: [0.5, 50]
stem_kernel_size: 3
stem_stride: 1
hidden_dims: [64, 64, 64, 128, 128]
apply_mask: True
downsample_mode: linear
