clip_val: 65504 # 65504 is the maximum value for 16-bit signed integer
ref_voltage: 1000
apply_filter: false
cutoff_freqs: [null, null]
reject_freq: null
drop_leftmost_nulls: false
pad_mode: constant
device: cuda
down_sampling_rate: 5
